title: Chandana Arutla
logo: /assets/meee.jpg
description: Data Analyst | ML Engineer
Education
Parul University, Gujarat(_2020-2024_)
BTech, CSE with Artificial Intelligence Specialization
theme: jekyll-theme-minimal
