title: Chandana Arutla
description: Data Analyst | ML Engineer

Education

- Parul University, Gujarat (_2020 - 2024_)
  
  BTech, Computer Science Engineering with Artificial Intelligence specialization

logo: /assets/img/headshot_circle.png
theme: jekyll-theme-minimal
